In [42]:
import pandas as pd
import numpy as np

bd = "bank-additional-full.csv"
names = ['age', 'job', 'marital', 'education', 'default', 'housing', 'loan', 'contact','month','day_of_week',
        'duration','campaign','pdays','previous','poutcome','emp.var.rate','cons.price.idx','cons.conf.idx','euribor3m',
        'nr.employed','y']
data = pd.read_csv(bd, names=names)

In [43]:
# age: edad de entrevistado
# job: tipo de ocupacion "admin.","blue-collar","entrepreneur","housemaid","management","retired","self-employed","services","student","technician","unemployed","unknown"
# marital: estado civel "divorced","married","single","unknown"
#education: grado de educacion "basic.4y","basic.6y","basic.9y","high.school","illiterate","professional.course","university.degree","unknown"
#default:  tiene el crédito por defecto? "yes","no"
#housing: tiene prestamo de vivienda "yes","no"
#loan: tuene prestamo personal? "yes","no"
#contact: comunicación de contacto "telephone","cellular"
#month: último contacto mes del año "jan", "feb", "mar", ..., "nov", "dec"
#day_of_week: last contact day of the week (categorical: "mon","tue","wed","thu","fri")
#duration: Duración del último contacto, en segundos. numero
#campaign: cantidad de veces contactado, numero
#pdays: la cantidad de días que pasaron después de que el cliente 
#fue contactado por última vez desde una campaña anterior 
#(numérico, -1 significa que el cliente no fue contactado previamente)
#previous: número de contactos realizados antes de esta campaña y para este cliente (numérico)
#poutcome: Resultado de la campaña de marketing anterior. "unknown","other","failure","success"
#emp.var.rate: tasa de variación del empleo - indicador trimestral (numérico)
#cons.price.idx: índice de precios al consumidor - indicador mensual (numérico)
#cons.conf.idx: consumer confidence index - monthly indicator (numeric) 
#euribor3m: Euribor tasa de 3 meses - indicador diario (numérico)
#nr.employed: número de empleados - indicador trimestral (numérico)
#y: ¿El cliente ha suscrito un depósito a plazo? "yes","no"
data

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,...,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y
0,56,housemaid,married,basic.4y,no,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93994.0,-36.4,4857.00,5191.0,no
1,57,services,married,high.school,unknown,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93994.0,-36.4,4857.00,5191.0,no
2,37,services,married,high.school,no,yes,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93994.0,-36.4,4857.00,5191.0,no
3,40,admin.,married,basic.6y,no,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93994.0,-36.4,4857.00,5191.0,no
4,56,services,married,high.school,no,no,yes,telephone,may,mon,...,1,999,0,nonexistent,1.1,93994.0,-36.4,4857.00,5191.0,no
5,45,services,married,basic.9y,unknown,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93994.0,-36.4,4857.00,5191.0,no
6,59,admin.,married,professional.course,no,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93994.0,-36.4,4857.00,5191.0,no
7,41,blue-collar,married,unknown,unknown,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93994.0,-36.4,4857.00,5191.0,no
8,24,technician,single,professional.course,no,yes,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93994.0,-36.4,4857.00,5191.0,no
9,25,services,single,high.school,no,yes,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93994.0,-36.4,4857.00,5191.0,no
10,41,blue-collar,married,unknown,unknown,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93994.0,-36.4,4857.00,5191.0,no
11,25,services,single,high.school,no,yes,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93994.0,-36.4,4857.00,5191.0,no
12,29,blue-collar,single,high.school,no,no,yes,telephone,may,mon,...,1,999,0,nonexistent,1.1,93994.0,-36.4,4857.00,5191.0,no
13,57,housemaid,divorced,basic.4y,no,yes,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93994.0,-36.4,4857.00,5191.0,no
14,35,blue-collar,married,basic.6y,no,yes,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93994.0,-36.4,4857.00,5191.0,no
15,54,retired,married,basic.9y,unknown,yes,yes,telephone,may,mon,...,1,999,0,nonexistent,1.1,93994.0,-36.4,4857.00,5191.0,no
16,35,blue-collar,married,basic.6y,no,yes,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93994.0,-36.4,4857.00,5191.0,no
17,46,blue-collar,married,basic.6y,unknown,yes,yes,telephone,may,mon,...,1,999,0,nonexistent,1.1,93994.0,-36.4,4857.00,5191.0,no
18,50,blue-collar,married,basic.9y,no,yes,yes,telephone,may,mon,...,1,999,0,nonexistent,1.1,93994.0,-36.4,4857.00,5191.0,no
19,39,management,single,basic.9y,unknown,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93994.0,-36.4,4857.00,5191.0,no
20,30,unemployed,married,high.school,no,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93994.0,-36.4,4857.00,5191.0,no
21,55,blue-collar,married,basic.4y,unknown,yes,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93994.0,-36.4,4857.00,5191.0,no
22,55,retired,single,high.school,no,yes,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93994.0,-36.4,4857.00,5191.0,no
23,41,technician,single,high.school,no,yes,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93994.0,-36.4,4857.00,5191.0,no
24,37,admin.,married,high.school,no,yes,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93994.0,-36.4,4857.00,5191.0,no
25,35,technician,married,university.degree,no,no,yes,telephone,may,mon,...,1,999,0,nonexistent,1.1,93994.0,-36.4,4857.00,5191.0,no
26,59,technician,married,unknown,no,yes,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93994.0,-36.4,4857.00,5191.0,no
27,39,self-employed,married,basic.9y,unknown,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93994.0,-36.4,4857.00,5191.0,no
28,54,technician,single,university.degree,unknown,no,no,telephone,may,mon,...,2,999,0,nonexistent,1.1,93994.0,-36.4,4857.00,5191.0,no
29,55,unknown,married,university.degree,unknown,unknown,unknown,telephone,may,mon,...,1,999,0,nonexistent,1.1,93994.0,-36.4,4857.00,5191.0,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41158,35,technician,divorced,basic.4y,no,no,no,cellular,nov,tue,...,1,999,0,nonexistent,-1.1,94767.0,-50.8,1035.00,4963.6,yes
41159,35,technician,divorced,basic.4y,no,yes,no,cellular,nov,tue,...,1,9,4,success,-1.1,94767.0,-50.8,1035.00,4963.6,yes
41160,33,admin.,married,university.degree,no,no,no,cellular,nov,tue,...,1,999,0,nonexistent,-1.1,94767.0,-50.8,1035.00,4963.6,yes
41161,33,admin.,married,university.degree,no,yes,no,cellular,nov,tue,...,1,999,1,failure,-1.1,94767.0,-50.8,1035.00,4963.6,no
41162,60,blue-collar,married,basic.4y,no,yes,no,cellular,nov,tue,...,2,4,1,success,-1.1,94767.0,-50.8,1035.00,4963.6,no
41163,35,technician,divorced,basic.4y,no,yes,no,cellular,nov,tue,...,3,4,2,success,-1.1,94767.0,-50.8,1035.00,4963.6,yes
41164,54,admin.,married,professional.course,no,no,no,cellular,nov,tue,...,2,10,1,success,-1.1,94767.0,-50.8,1035.00,4963.6,yes
41165,38,housemaid,divorced,university.degree,no,no,no,cellular,nov,wed,...,2,999,0,nonexistent,-1.1,94767.0,-50.8,1.03,4963.6,yes
41166,32,admin.,married,university.degree,no,no,no,telephone,nov,wed,...,1,999,1,failure,-1.1,94767.0,-50.8,1.03,4963.6,yes
41167,32,admin.,married,university.degree,no,yes,no,cellular,nov,wed,...,3,999,0,nonexistent,-1.1,94767.0,-50.8,1.03,4963.6,no
41168,38,entrepreneur,married,university.degree,no,no,no,cellular,nov,wed,...,2,999,0,nonexistent,-1.1,94767.0,-50.8,1.03,4963.6,no
41169,62,services,married,high.school,no,yes,no,cellular,nov,wed,...,5,999,0,nonexistent,-1.1,94767.0,-50.8,1.03,4963.6,no
41170,40,management,divorced,university.degree,no,yes,no,cellular,nov,wed,...,2,999,4,failure,-1.1,94767.0,-50.8,1.03,4963.6,no
41171,33,student,married,professional.course,no,yes,no,telephone,nov,thu,...,1,999,0,nonexistent,-1.1,94767.0,-50.8,1031.00,4963.6,yes
41172,31,admin.,single,university.degree,no,yes,no,cellular,nov,thu,...,1,999,0,nonexistent,-1.1,94767.0,-50.8,1031.00,4963.6,yes
41173,62,retired,married,university.degree,no,yes,no,cellular,nov,thu,...,1,999,2,failure,-1.1,94767.0,-50.8,1031.00,4963.6,yes
41174,62,retired,married,university.degree,no,yes,no,cellular,nov,thu,...,1,1,6,success,-1.1,94767.0,-50.8,1031.00,4963.6,yes
41175,34,student,single,unknown,no,yes,no,cellular,nov,thu,...,1,999,2,failure,-1.1,94767.0,-50.8,1031.00,4963.6,no
41176,38,housemaid,divorced,high.school,no,yes,yes,cellular,nov,thu,...,1,999,0,nonexistent,-1.1,94767.0,-50.8,1031.00,4963.6,no
41177,57,retired,married,professional.course,no,yes,no,cellular,nov,thu,...,6,999,0,nonexistent,-1.1,94767.0,-50.8,1031.00,4963.6,no
41178,62,retired,married,university.degree,no,no,no,cellular,nov,thu,...,2,6,3,success,-1.1,94767.0,-50.8,1031.00,4963.6,yes
41179,64,retired,divorced,professional.course,no,yes,no,cellular,nov,fri,...,3,999,0,nonexistent,-1.1,94767.0,-50.8,1028.00,4963.6,no
41180,36,admin.,married,university.degree,no,no,no,cellular,nov,fri,...,2,999,0,nonexistent,-1.1,94767.0,-50.8,1028.00,4963.6,no
41181,37,admin.,married,university.degree,no,yes,no,cellular,nov,fri,...,1,999,0,nonexistent,-1.1,94767.0,-50.8,1028.00,4963.6,yes
41182,29,unemployed,single,basic.4y,no,yes,no,cellular,nov,fri,...,1,9,1,success,-1.1,94767.0,-50.8,1028.00,4963.6,no
41183,73,retired,married,professional.course,no,yes,no,cellular,nov,fri,...,1,999,0,nonexistent,-1.1,94767.0,-50.8,1028.00,4963.6,yes
41184,46,blue-collar,married,professional.course,no,no,no,cellular,nov,fri,...,1,999,0,nonexistent,-1.1,94767.0,-50.8,1028.00,4963.6,no
41185,56,retired,married,university.degree,no,yes,no,cellular,nov,fri,...,2,999,0,nonexistent,-1.1,94767.0,-50.8,1028.00,4963.6,no
41186,44,technician,married,professional.course,no,no,no,cellular,nov,fri,...,1,999,0,nonexistent,-1.1,94767.0,-50.8,1028.00,4963.6,yes
41187,74,retired,married,professional.course,no,yes,no,cellular,nov,fri,...,3,999,1,failure,-1.1,94767.0,-50.8,1028.00,4963.6,no

In [48]:
# promedio de edad segun "marital "
single_pro_edad =data[data['marital']=='single']['age'].mean()
married_pro_edad =data[data['marital']=='married']['age'].mean()
divorced_pro_edad = data[data['marital']=='divorced']['age'].mean()

print(single_pro_edad)
print(married_pro_edad)
print(divorced_pro_edad)

33.15871369294606
42.30716463414634
44.89939288811795